query HomeQuery($locale: I18NLocaleCode) {
  home(locale: $locale) {
    Carrousel {
      ... on ComponentImageWithLinkImageWithLink {
        Link
        TypeOfLink
        Title
        Image {
          formats
          url
          height
          width
          hash
        }
      }
      ... on ComponentDataContentDataContent {
        data_contents {
          Slug
          Title
          Banner {
            formats
            url
            height
            width
            hash
          }
        }
      }
    }
    latest_news {
      Title
      Image {
        url
        width
        height
        formats
      }
      Link
      TypeOfLink
    }
    Promos {
      ... on ComponentDataContentDataContent {
        data_contents {
          Slug
          Title
          Promo {
            url
            width
            height
            formats
            hash
          }
        }
      }
      ... on ComponentImageWithLinkImageWithLink {
        Link
        TypeOfLink
        Title
        Image {
          url
          width
          height
          hash
          formats
        }
      }
    }
    reading_recommendations {
      Link
      Title
      TypeOfLink
      Image {
        width
        height
        hash
        url
        formats
      }
    }
    do_not_miss_it {
      Title
      Link
      TypeOfLink
      Image {
        url
        width
        height
        formats
      }
    }
  }
}
