query NewsQuery($locale: I18NLocaleCode) {
  newsGallery(locale: $locale) {
    Banners {
      Title
      Link
      Image {
        mime
        width
        height
        formats
        url
        hash
      }
      TypeOfLink
    }
    News_vault(pagination: { limit: 100 }) {
      Tittle
      Source
      Link
    }
    News(pagination: { limit: 20 }) {
      Title
      Link
      TypeOfLink
      Image {
        url
        width
        height
        formats
        mime
      }
    }
  }
}
